version: "2"
catalog:
  name: "EEA - RabbitMQ"
  description: "Robust messaging for applications"
  version: "3.7.28-2"
  questions:
  - variable: "VARIABLE_NAME"
    label: "LABEL0"
    description: "DESCRIPTION"
    type: "password"
  - variable: "HOST_LABELS"
    label: "Schedule services on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    type: "string"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    type: "string"
    required: true
  - variable: "RABBITMQ_DEFAULT_USER"
    label: "RabbitMQ default user"
    description: "RabbitMQ user to access the management console."
    default: "guest"
    type: "string"
    required: true
  - variable: "RABBITMQ_DEFAULT_PASS"
    label: "RabbitMQ default password"
    description: "RabbitMQ password to access the management console."
    type: "password"
    required: true
    default: "guest"
  - variable: "MEMORY_RESERVATION"
    label: "Rabbitmq memory reservation"
    description: "Memory reservation"
    default: "1g"
    type: "string"
    required: true
  - variable: "MEMORY_LIMIT"
    label: "Rabbitmq memory limit"
    description: "Memory limit"
    default: "1g"
    type: "string"
    required: true      
  - variable: "VOLUME"
    label: "Rabbitmq data volume name"
    description: "Volume name (without '-' if using netapp volume driver)"
    default: "rabbitmq"
    type: "string"
    required: true
  - variable: "VOLUME_EXTERNAL"
    label: "Rabbitmq data volume environment scoped (external)"
    description: "External volume in order to have a fixed name and be shareable between environments. Needs to be manually created in Rancher, Storage"
    default: "no"
    type: "enum"
    options:
    - "yes"
    - "no" 
  - variable: "VOLUME_DRIVER"
    label: "Data volume driver"
    description: "Volume driver for rabbitmq"
    default: "rancher-ebs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    - "local"
    required: true
  - variable: "VOLUME_DRIVER_OPTS"
    label: "Data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"

services:
  rabbitmq:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5672
      unhealthy_threshold: 5
      initializing_timeout: 120000
      interval: 10000
      strategy: recreate
