version: '2'
catalog:
  name: "Converters"
  description: 
  version: "2021-05-05T1556"
  questions:
  - variable: "MYSQL_DATABASE"
    label: "Database name"
    type: "string"
    required: true
  - variable: "MYSQL_PASSWORD"
    label: "Database password"
    type: "string"
    required: true
  - variable: "MYSQL_ROOT_PASSWORD"
    label: "Database root password"
    type: "string"
    required: true
  - variable: "MYSQL_USER"
    label: "Database user"
    type: "string"
    required: true
  - variable: "CATALINA_OPTS"
    label: "CATALINA_OPTS"
    type: "string"
    required: true
  - variable: "XQueryPassword"
    label: "XQueryPassword"
    type: "string"
    required: true
  - variable: "XQueryUser"
    label: "XQueryUser"
    type: "string"
    required: true
  - variable: "converters_files_volume"
    label: "Files volume"
    type: "string"
    required: true
  - variable: "converters_mysql_volume"
    label: "MySQL volume"
    type: "string"
    required: true
  - variable: "DATA_VOLUME_DRIVER"
    label: "Volumes driver"
    description: "Volumes driver to be used"
    default: "rancher-nfs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    required: true

services:
  cron:
    scale: 1
    start_on_create: true
  dbservice:
    scale: 1
    start_on_create: true
  tomcat:
    scale: 3
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 3500
      port: 8080
      unhealthy_threshold: 3
      interval: 20000
      strategy: recreate
      request_line: GET "/api/latestJobStartTime" "HTTP/1.0"
  administration:
    scale: 1
    start_on_create: true
  converters-rsynch:
    scale: 1
    start_on_create: true
