name: "Rancher crontab container"
description: "[DEPRECATED] EEA rancher controlled crontab container to perform all cron tasks for docker containers"
version: "1.0"
category: "Applications"
license: "GPLv3"
