version: '2'
services:
  nfs-volumes:
    image: busybox
    tty: true
    stdin_open: true
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      io.rancher.container.start_once: 'true'
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-downloads:/data/downloads
    - www-suggestions:/data/suggestions
    - www-static-resources:/data/www-static-resources
    - www-ssl-certs:/data/www-ssl-certs
    - www-postgres-dump:/data/postgresql.backup
    - www-apache-logs:/data/apache-logs
    volume_driver: ${NFS_VOLUME_DRIVER}
    command: ["ls", "-l", "/var/lib/postgresql/archive"]
