version: '2'
catalog:
  name: "EEA WWW - Volumes"
  description: "Prepare Docker volumes needed by EEA WWW"
  version: "3.4"
  uuid: "www-volumes-7"
  questions:
  - variable: "NFS_VOLUME_DRIVER"
    label: "NFS Volume Driver"
    description: "Docker volume driver to be used for shared volumes"
    default: "rancher-nfs"
    required: true
    type: "enum"
    options:
    - "rancher-nfs"
    - "local"
  - variable: "HOST_LABELS"
    label: "Schedule services on hosts with the following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling services"
    default: "frontend=yes"
    type: "string"
    required: true
