version: '2'
services:
  metricbeat:
    image: eeacms/metricbeat:6.3-1.0
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: metricbeat=ignore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: ${mem_limit}
    mem_reservation: ${mem_reservation}
    environment:
      CONFIG: "${CONFIG}"
      ES_URL:  "${ES_URL}" 
      ES_USER:  "${ES_USER}"
      ES_PASSWORD:  "${ES_PASSWORD}"
      RANCHER_METADATA: "yes"
      CHECK_INTERVAL: "${CHECK_INTERVAL}"
      TAGS: "${TAGS}"
      TZ: "${TZ}"
     
