name: "Rancher to Redmine exporter"
description: |
  Exports a list of rancher stacks, hosts and containers to a redmine wiki.
version: "1.0"
maintainer: "EEA: IDM2 A-Team"
minimum_rancher_version: v1.0.2
category: "Tools"
