version: '2'
volumes:

  {{ .Values.DATA_VOLUME_NAME }}:
    driver: {{ .Values.DATA_VOLUME_DRIVER }}
    {{- if eq .Values.DATA_VOLUME_EXTERNAL "yes"}}
    external: true
    {{- end}}
    {{- if .Values.DATA_VOLUME_DRIVER_OPTS}}
    driver_opts:
      {{.Values.DATA_VOLUME_DRIVER_OPTS}}
    {{- end}}

  fise_zeodb:

services:
  memcached:
    image: memcached:1.5.20
    environment:
      TZ: Europe/Copenhagen
    mem_reservation: ${CACHE_SIZE}m
    mem_limit: ${CACHE_SIZE}m
    labels:
      io.rancher.container.hostname_override: container_name
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
    environment:
      TZ: "${TZ}"
    command:
    - "-m"
    - "${CACHE_SIZE}"

  zeo:
    mem_limit: ${ZEO_MEM_LIMIT}
    image: plone/plone:5.2-python2
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: zeo
    volumes:
    - {{.Values.DATA_VOLUME_NAME}}:/data
    mem_reservation: ${ZEO_MEM_RES}
    command:
    - zeo
    labels:
      io.rancher.container.hostname_override: container_name
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}


  plone:
    mem_limit: ${PLONE_MEM_LIMIT}
    image: tiberiuichim/fise-plone:2.0
    environment:
      SENTRY_DSN: "${SENTRY_DSN}"
      TZ: "${TZ}"
      ZEO_ADDRESS: zeo:8080
      ZOPE_MODE: zeo_client
    mem_reservation: ${PLONE_MEM_RES}
    depends_on:
    - zeo
    - memcached
    links:
    - zeo
    - memcached
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      

  frontend:
    image: tiberiuichim/fise-frontend:3.1
    mem_limit: ${FRONT_MEM_LIMIT}
    mem_reservation: ${FRONT_MEM_RES}
    depends_on:
    - plone
    links:
    - plone
    environment:
      API_PATH: ${API_PATH}
      {{- if eq .Values.FRONTEND_DEBUG "Yes" }}
      DEBUG: '*'
      {{- end}}
      INTERNAL_API_PATH: ${INTERNAL_API_PATH}
      PORT: '3000'
      SENTRY_DSN: "${SENTRY_DSN}"
      TZ: "${TZ}"
    labels:
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name


