version: '2'
catalog:
  name: "Forests - Plone 5"
  description: "Volto-based Plone 5 stack for Forests Information System (FISE)"
  version: "5.2-4"
  questions:
  - variable: "HOST_LABELS"
    label: "Schedule services on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to use when scheduling the services."
    type: "string"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "SENTRY_DSN"
    label: "Sentry DSN"
    description: "Sentry client key. If set, Sentry error reporting and User feedback will be enabled. Default is plone-saas DSN."
    type: "string"
    required: false
    default: ""
  - variable: "API_PATH"
    label: "API_PATH Variable"
    description: "Hosted website name, used as API_PATH variable"
    default: "https://demo-forests-p5.eea.europa.eu/api"
    required: true
    type: "string"
  - variable: "INTERNAL_API_PATH"
    label: "INTERNAL_API_PATH Variable"
    description: "Location of Plone site accessible from container"
    default: "http://plone:8080/fise"
    required: true
    type: "string"
  - variable: "FRONTEND_DEBUG"
    label: "Enable debug on frontend"
    default: "Yes"
    type: "enum"
    options:
    - "Yes"
    - "No"
    required: true
  - variable: "CACHE_SIZE"
    label: "Memcached cache size and memory limit, in MB"
    default: "128"
    required: true
    type: "int"
  - variable: "ZEO_MEM_RES"
    label: "Zeo container memory reservation"
    description: "At least 512m"
    type: "string"
    default: "512m"
    required: true
  - variable: "ZEO_MEM_LIMIT"
    label: "Zeo container memory limit"
    description: "At least 512m"
    type: "string"
    default: "512m"
    required: true
  - variable: "PLONE_MEM_RES"
    label: "Plone containers memory reservation"
    description: "At least 512m"
    type: "string"
    default: "512m"
    required: true
  - variable: "PLONE_MEM_LIMIT"
    label: "Plone containers memory limit"
    description: "At least 1g"
    type: "string"
    default: "1g"
    required: true
  - variable: "FRONT_MEM_RES"
    label: "Frontend containers memory reservation"
    description: "At least 512m"
    type: "string"
    default: "512m"
    required: true
  - variable: "FRONT_MEM_LIMIT"
    label: "Frontend containers memory limit"
    description: "At least 512m"
    type: "string"
    default: "512m"
    required: true
  - variable: "DATA_VOLUME_NAME"
    label: "Data volume name"
    default: "fise_zeodb"
    type: "string"
    required: true
  - variable: "DATA_VOLUME_DRIVER"
    label: "Data volume driver"
    description: "Volume driver for zeo data"
    default: "rancher-nfs"
    type: "enum"
    options:
    - "netapp"
    - "rancher-nfs"
    - "rancher-ebs"
    required: true
  - variable: "DATA_VOLUME_EXTERNAL"
    label: "Data volume environment scoped (external)"
    description: "Data Volume is environment scoped (externally created by other stack or manually created in Storage)"
    default: "yes"
    type: "enum"
    required: true
    options:
    - "yes"
    - "no"
  - variable: "DATA_VOLUME_DRIVER_OPTS"
    label: "Data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` and `netapp` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"


services:
  plone:
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET /
  zeo:
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  memcached:
    health_check:
      port: 11211
      interval: 2000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 2000
      healthy_threshold: 2
  frontend:
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000

