.catalog:
  name: "eea-es-bootstrap-CaR"
  version: "2.0.14"
  description: "EEA Elastic bootstrap based Countries and Regions"
  questions:
    - variable: "APP_PORT"
      label: "Application exposed port"
      description: "Countries and Regions application exposed port"
      type: "int"
      default: 65344
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: es_index_name
      description: "Set the name of the elasticsearch index contaning the Country tagged content."
      label: "Index name"
      type: "string"
      required: true
      default: rdfdata
    - variable: RO_USER
      description: "Read only username"
      label: "Read only username"
      type: "string"
      required: true
      default: "ro"
    - variable: RO_PASSWORD
      description: "Read only user password"
      label: "Read only user password"
      type: "password"
      required: true
      default: "rotest"
    - variable: RW_USER
      description: "RW Username"
      label: "Username with write access"
      type: "string"
      required: true
      default: "rw"
    - variable: RW_PASSWORD
      description: "Read/Write user password"
      label: "Password for RW user"
      type: "password"
      required: true
      default: "rwtest"
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      default: esbootstrap=yes
    - variable: "SENTRY_DSN"
      label: "Sentry DSN"
      description: "Sentry private DSN"
      type: "string"
    - variable: "VOLUME_DRIVER"
      label: "Configuration volume driver"
      default: "rancher-nfs"
      type: "enum"
      options:
      - "rancher-nfs"
      - "netapp"
      - "rancher-ebs"
      required: true
    - variable: "VOLUME_DRIVER_OPT"
      label: "Configuration volume driver options"
      description: |
          Specify "driver_opts" key/value pair in the format "optionName: optionValue".
          E.g. for the `rancher-ebs` and `netapp` drivers you should specify the required 'size' option like this: "size: 1".
      type: "multiline"
    - variable: "app_mem_reservation"
      type: "string"
      required: true
      label: "Memory reservation esapp service"
      description: "Memory reservation per container. Recommended - 512m"
      default: "512m"
    - variable: "app_mem_limit"
      type: "string"
      required: true
      label: "Memory limit esapp service"
      description: "Memory limit per container. Recommended - 1g"
      default: "1g"
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"
esapp:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
