version: '2'

volumes:
  {{ .Values.DATA_VOLUME_NAME }}:
    driver: {{ .Values.DATA_VOLUME_DRIVER }}
    {{- if eq .Values.DATA_VOLUME_EXTERNAL "yes"}}
    external: true
    {{- end}}
    {{- if .Values.DATA_VOLUME_DRIVER_OPTS}}
    driver_opts:
      {{.Values.DATA_VOLUME_DRIVER_OPTS}}
    {{- end}}

services:
    screenshoteer:
        mem_limit: 1024m
        mem_reservation: 512m
        image: eeacms/screenshoteer:0.9
        ports:
          - "3000"
        cap_add:
          - SYS_ADMIN
        init: true
        environment:
          VOLUME: ${VOLUME_PATH}
          CHROME_DEVEL_SANDBOX: ${CHROME_SANDBOX}
          SENTRY_DSN: ${SENTRY_DSN}
          TZ: ${TZ}
        volumes:
          - {{.Values.DATA_VOLUME_NAME}}:${VOLUME_PATH}:z
        labels:
          io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
          io.rancher.container.hostname_override: container_name
          io.rancher.scheduler.affinity:host_label_ne: ${HOST_LABELS}

    # {{- if eq .Values.UPDATE_SYSCTL "true" }}
    # es-sysctl:
    #     labels:
    #         io.rancher.scheduler.global: 'true'
    #         {{- if .Values.host_labels}}
    #         io.rancher.scheduler.affinity:host_label: ${host_labels}
    #         {{- else}}
    #         io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    #         {{- end}}
    #         io.rancher.container.start_once: false
    #     network_mode: none
    #     image: rawmind/alpine-sysctl:0.1
    #     privileged: true
    #     mem_limit: 32m
    #     mem_reservation: 8m
    #     environment:
    #         - "SYSCTL_KEY=kernel.unprivileged_userns_clone"
    #         - "SYSCTL_VALUE=1"
    #         - "KEEP_ALIVE=1"
    # {{- end}}
