version: "2"
services:
  apache:
    image: eeacms/apache:2.4-2.6
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - varnish
    environment:
      APACHE_MODULES: "${APACHE_MODULES}"
      APACHE_CONFIG: "${APACHE_CONFIG}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads

  varnish:
    image: eeacms/varnish-copernicus-land:1.3
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      VARNISH_BACKEND_HOST: haproxy
      VARNISH_BACKEND_PORT: '5000'
      VARNISH_MEMORY: 2G
      LOGSPOUT: "ignore"
    links:
    - haproxy

  haproxy:
    image: eeacms/haproxy:1.8-1.5
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    ports:
    - "1936:1936"
    links:
    - plone
    environment:
      TZ: "${TZ}"
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      TIMEOUT_SERVER: "180000"
      TIMEOUT_CLIENT: "180000"
      STATS_AUTH: "${HAPROXY_STATS_AUTH}"

  memcached:
    image: memcached:1.5.20
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - "2048"

  postfix:
    {{- if eq .Values.VOLUME_PREFIX "demo"}}
    image: eaudeweb/mailtrap:2.3
    ports:
    - "80"
   {{- else}}
    image: eeacms/postfix:eionet
    environment:
      TZ: "${TZ}"
      MTP_HOST: "eea.europa.eu"
   {{- end}}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  plone:
    image: eeacms/plone-copernicus-land:19.11.8-2.113
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_client"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads

  async:
    image: eeacms/plone-copernicus-land:19.11.8-2.113
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_async"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads

  cron-subscrib-reset:
    image: eeacms/plone-copernicus-land:19.11.8-2.113
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      cron.schedule: 0 0 * * *
    links:
    - zeoserver
    - memcached
    - postfix
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_client"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    entrypoint:
    - bin/zeo_client
    - run
    - bin/subscrib_reset
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads

  zeoserver:
    image: plone/zeoserver:2.13.23-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_data:/data
    environment:
      TZ: "${TZ}"

  sync-proxy:
    image: nginx:1.17-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      NGINX_CONF: "${SYNC_PROXY_CONFIG}"
    command:
      - /bin/sh
      - -c
      - 'echo $$NGINX_CONF > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    restart: "always"


  landfiles-sync:
    image: eeacms/copernicus-land-scripts:sync-1.1
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      SOURCE_DIRECTORY: "${SYNC_REMOTE_PATH}"
      TARGET_DIRECTORY: "${SYNC_TARGET_PATH}"
      RCLONE_CONFIG_REMOTE_URL: "${SYNC_REMOTE_URL}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads

  landfiles-cleanup:
    image: eeacms/copernicus-land-scripts:cleanup-1.0
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      TARGET_DIRECTORY: /downloads/landfiles/dst/
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads


volumes:
  {{ .Values.VOLUME_PREFIX }}land_data:
    driver: ${DATA_VOLUME_DRIVER}
    external: true
  {{ .Values.VOLUME_PREFIX }}land_downloads:
    driver: ${DOWNLOADS_VOLUME_DRIVER}
    external: true
