name: "Content Registry"
description: "Content Registry"
version: "2021-08-10T0913"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.rancher.catalog/blob/master/templates/contreg/README.md
labels:
  io.rancher.certified: EEA
