name: "Clair - Vulnerability Analysis"
description: "EEA Clair Vulnerability Analysis for docker containers"
version: "1.1"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
