name: "EEA - Celery"
description: "Celery RabbitMQ message consumer"
version: "0.1"
category: "Message queues"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.celery
labels:
  io.rancher.certified: EEA
