name: "Converters"
description: "Conversion and Quality Assessment Service"
version: "2021-05-18T1111"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://converters.eionet.europa.eu
labels:
  io.rancher.certified: EEA