name: "Datadict"
description: "Data Dictionary"
version: "2021-07-29T1032"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.rancher.catalog/blob/master/templates/datadict/README.md
labels:
  io.rancher.certified: EEA
