name: "Energy Union - Plone"
description: "Plone 5 Energy Union Website"
version: "5.2-2"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/eea.docker.plone.energy-union
labels:
  io.rancher.certified: EEA
