name: "Volto"
description: "Volto: A generic React-based frontend for Plone (or Guillotina)"
version: "0.1"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
