name: "EEA - RIOT/MATRIX"
description: "EEA Matrix server with riot web client and LDAP integration"
version: "1.8"
category: "Chat"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
