version: '2'
catalog:
  name: "Volto - CLMS"
  description: "Volto - CLMS: React-based frontend"
  version: "0"
  questions:
  - variable: "BACKEND"
    label: "Backend"
    description: "Plone backend service"
    type: "service"
    required: true
  - variable: "FRONTEND"
    label: "Frontend"
    description: "Plone frontend"
    type: "service"
    required: true
 

services:
  frontend:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
