version: "2"
catalog:
  name: "Logcentral"
  description: "EEA Centralized logging based on Docker and Graylog2"
  version: "9"
  uuid: "logcentral-graylog-9"
  questions:
  - variable: "graylog_master_url"
    description: "Select the URL of graylog master"
    label: "Graylog URL"
    type: "string"
    required: true
    default: "logs.eea.europa.eu"
  - variable: "graylog_frontend_host_labels"
    label: "Schedule Graylog frontend services on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    type: "string"
    required: true
    default: "frontend=yes"
  - variable: "graylog_master_host_labels"
    label: "Schedule Graylog master on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    type: "string"
    required: true
    default: "logcentral-master=yes"
  - variable: "graylog_client_host_labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    label: "Schedule Graylog clients on hosts with following host labels"
    type: "string"
    required: true
    default: "logcentral-client=yes"
  - variable: "graylog_db_host_labels"
    label: "Schedule Mongodb on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    type: "string"
    required: true
    default: "logcentral-db=yes"
  - variable: "postfix_mtp_user"
    label: "Postfix user"
    description: "Postfix user name to connect to SMTP relay"
    type: "string"
    required: true
    default: "logcentral"
  - variable: "postfix_mtp_password"
    label: "Postfix password"
    description: "Postfix password to connect to SMTP relay"
    type: "password"
    required: true
  - variable: "graylog_root_password"
    label: "Graylog root password SHA2"
    description: "Graylog root password SHA256 encrypted. Create one by using for example: echo -n yourpassword | shasum -a 256"
    type: "string"
    required: true
  - variable: "graylog_secret"
    label: "Graylog secret password"
    description: "Select a secret to secure/pepper the stored user passwords. At least 16 characters. Generate one by using for example: pwgen -N 1 -s 96"
    type: "string"
    required: true
  - variable: "graylog_heap_size"
    label: "Graylog Java VM heap size values"
    description: "Specify the Java VM heap size values by using the arguments -Xms<size> (set initial Java heap size), -Xmx<size> (set maximum Java heap size) and -Xss<size> (sets java thread stack size)"
    default: "-Xms2g -Xmx4g"
    type: "string"
    required: true
  - variable: "graylog_processbuffer_processors"
    label: "Graylog number of Processbuffer processors"
    description: "Default 5, increase if not enough"
    default: 20
    type: "int"
  - variable: "elasticsearch_link"
    label: "Elasticsearch stack/service"
    description: "stack/service link or external service link to elasticsearch cluster. Must have the web interface open on port 9200"
    default: "logcentral-elasticsearch/elasticsearch-clients"
    required: true
    type: "service"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    type: "string"
    required: true
  - variable: "data_volume_driver"
    label: "Graylog data volume driver"
    description: "Graylog Data Volume driver ( ex journals ), must be at least 6GB"
    default: "rancher-ebs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "data_volume_driver_opts"
    label: "Graylog data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 10".
    type: "multiline"
  - variable: "volume_driver"
    label: "DB data volume driver"
    description: "Volume driver"
    default: "rancher-ebs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "volume_driver_opts"
    label: "DB data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"

services:
  apache:
    scale: 1
    health_check:
      port: 443
      interval: 60000
      initializing_timeout: 300000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  graylog-master:
    scale: 1
    health_check:
      port: 9000
      interval: 60000
      initializing_timeout: 300000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  graylog-client:
    scale: 2
    health_check:
      port: 9000
      interval: 60000
      initializing_timeout: 300000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  mongo:
    scale: 1
    health_check:
      port: 27017
      interval: 60000
      initializing_timeout: 300000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  loadbalancer:
    scale: 1
