.catalog:
  name: "eea-es-bootstrap-CO2-passenger-cars"
  version: "1.0.5"
  description: "CO2 emmisions from passenger cars — Elastic app"
  uuid: eea-es-bootstrap-CO2-passenger-cars-5
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: RO_USER
      description: "Read only username"
      label: "Read only username"
      type: "string"
      required: true
      default: "ro"
    - variable: RO_PASSWORD
      description: "Read only user password"
      label: "Read only user password"
      type: "password"
      required: true
      default: "rotest"
    - variable: RW_USER
      description: "RW Username"
      label: "Username with write access"
      type: "string"
      required: true
      default: "rw"
    - variable: RW_PASSWORD
      description: "Read/Write user password"
      label: "Password for RW Username"
      type: "password"
      required: true
      default: "rwtest"
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: esbootstrap=yes
    - variable: "SENTRY_DSN"
      label: "Sentry DSN"
      description: "Sentry private DSN"
      type: "string"
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"
esapp:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
