version: "2"

services:
  airflow-webserver:
    image: eeacms/airflow:0.0.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      AIRFLOW_VAR_INDEXED_WEBSITES: ${INDEXED_WEBSITES}
    command: webserver
    ports:
      - "8100:8080"

    restart: always

  airflow-scheduler:
    image: eeacms/airflow:0.0.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      AIRFLOW_VAR_INDEXED_WEBSITES: ${INDEXED_WEBSITES}
    command: scheduler
    restart: always

  airflow-worker:
    image: eeacms/airflow:0.0.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      AIRFLOW_VAR_INDEXED_WEBSITES: ${INDEXED_WEBSITES}
    command: celery worker
    restart: always

  airflow-init:
    image: eeacms/airflow:0.0.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    command: version
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      AIRFLOW_VAR_INDEXED_WEBSITES: ${INDEXED_WEBSITES}
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow

  flower:
    image: eeacms/airflow:0.0.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    user: "50000:50000"
    depends_on:
      - redis
      - postgres
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__CORE__PARALLELISM: 128
      AIRFLOW__CORE__DAG_CONCURRENCY: 64
      AIRFLOW_VAR_INDEXED_WEBSITES: ${INDEXED_WEBSITES}
    command: celery flower
    ports:
      - "5555:5555"

    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    restart: always
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name

  redis:
    image: redis:latest
    restart: always
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name

  rabbitmq:
    image: eeacms/rabbitmq:3.7.15-1
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      TZ: Europe/Copenhagen
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    volumes:
      - {{.Values.RABBITMQ_VOLUME}}:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  logstash:
    image: logstash:7.12.1
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    links:
      - 'elastic:'
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name

  ide:
    image: eeacms/cloud9
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/config
    ports:
      - '8080'
    environment:
      - C9_WORKSPACE=/config
      - TZ=${TZ}
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name
    depends_on:
      - eea-crawler-config

  eea-crawler-config:
    image: eeacms/eea-crawler:0.0.1
    environment:
      - github_repo=https://github.com/eea/eea-crawler
      - DEV_ENV=true
      - TZ=${TZ}
    volumes:
      - ${CRAWLER_CONFIG_VOLUME}:/custom_config
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      io.rancher.container.hostname_override: container_name

  elastic:
    external_links:
      - ${es_endpoint}
    image: rancher/dns-service


volumes:
  {{.Values.CRAWLER_CONFIG_VOLUME}}:
    external: true
    driver: ${CRAWLER_CONFIG_VOLUME_DRIVER}
    {{- if .Values.CRAWLER_CONFIG_VOLUME_DRIVER_OPTS}}
    driver_opts:
      {{.Values.CRAWLER_CONFIG_VOLUME_DRIVER_OPTS}}
    {{- end}}
  {{.Values.POSTGRES_VOLUME}}:
    external: true
    driver: ${POSTGRES_VOLUME_DRIVER}
    {{- if .Values.POSTGRES_VOLUME_DRIVER_OPTS}}
    driver_opts:
      {{.Values.POSTGRES_VOLUME_DRIVER_OPTS}}
    {{- end}}
  {{.Values.RABBITMQ_VOLUME}}:
    driver: ${RABBITMQ_VOLUME_DRIVER}
    external: true
    {{- if .Values.RABBITMQ_VOLUME_DRIVER_OPTS}}
    driver_opts:
      {{.Values.RABBITMQ_VOLUME_DRIVER_OPTS}}
    {{- end}}
