.catalog:
  name: "Airflow"
  version: "0.0.1"
  description: "Airflow with RabbitMQ and Logstash app"
  uuid: eea-airflow
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
    - variable: "eea_crawler_volume"
      label: "EEA Crawler volume name"
      default: "eeacrawler"
      type: "string"
      required: true
    - variable: "CRAWLER_VOLUME_DRIVER"
      label: "Data volumes driver"
      description: "Data volume driver, choose rancher_ebs only for Amazon"
      default: "netapp"
      type: "enum"
      options:
        - "rancher-ebs"
        - "netapp"
      required: true
    - variable: "CRAWLER_VOLUME_DRIVER_OPTS"
      label: "Data volume driver options"
      description: |
          Specify "driver_opts" key/value pair in the format "optionName: optionValue".
          E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
          Empty if  driver is not `rancher-ebs`.
      type: "multiline"
      default: "size: 5"
