.catalog:
  name: "Airflow"
  version: "0.0.1"
  description: "Airflow with RabbitMQ and Logstash app"
  uuid: eea-airflow
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: esbootstrap=yes
