version: '2'
catalog:
    name: Heartbeats Elasticsearch stack
    version: 6.3-1
    description: EEA Heartbeat stack to be used for monitoring
    uuid: heartbeat-0

    questions:
        - variable: "ES_URL"
          label: "ElasticSearch client url"
          description: "The ElasticSearch HTTP interface"
          type: "string"
          required: true
        - variable: ES_USER
          label: "Elasticsearch username"
          description: "Username with write access"
          type: "string"
        - variable: ES_PASSWORD
          label: "Elasticsearch user password"
          description: "Password for write access username"
          type: "password"
        - variable: KIBANA_URL
          label: "KIBANA url"
          description: "To be used to import dashboards"
          type: "string"
          default: "kibana"
        - variable: "CONFIG"
          label: "Custom configuration"
          description: "Will be used for overwriting the default configuration, does not need to contain output https://www.elastic.co/guide/en/beats/heartbeat/current/configuring-howto-heartbeat.html"
          type: "multiline"
          default: |
            heartbeat.monitors:
            - type: icmp
              schedule: '*/5 * * * * * *'
              hosts: ["examplehostname"]
            - type: tcp
              schedule: '@every 5s'
              hosts: ["examplehost:7"]  # default TCP Echo Protocol
              check.send: "Check"
              check.receive: "Check"
            - type: http
              schedule: '@every 5s'
              urls: ["http://example:80/service/status"]
              check.response.status: 200
            heartbeat.scheduler:
              limit: 10
          required: true
        - variable: "TZ"
          label: "Time zone"
          description: "Time zone"
          default: "Europe/Copenhagen"
          required: true
          type: "string"
