version: '2'
catalog:
  name: "Redmine wiki manager"
  description: "Enriches redmine wikis."
  version: "1.2"
  minimum_rancher_version: "v1.2.0"
  questions:
    - variable: "RANCHER_CONFIG"
      label: "Rancher configuration"
      description: "Multiline, with the format - rancher url, access key, secret key ( separated by commas)"
      type: "multiline"
    - variable: "SVN_USER"
      label: "SVN readonly user"
      description: "Used to read docker-compose.yml"
      type: "string"
    - variable: "SVN_PASSWORD"
      label: "SVN user password"
      description: "Used to read docker-compose.yml"
      type: "password"
    - variable: "RUN_SCHEDULE"
      label: "Crontab schedule (UTC)"
      default: "0 0 3 * * *"
      type: "string"
    - variable: "WIKI_SERVER"
      label: "Redmine url"
      default: "https://taskman.eionet.europa.eu/"
      description: "The main url of the redmine instance, if not given will export the result in STDOUT"
      type: "string"
    - variable: "WIKI_APIKEY"
      label: "Redmine API key"
      description: "Belongs to the user that will update the wiki pages, if not given will export the result in STDOUT"
      type: "password"
    - variable: "WIKI_PROJECT"
      label: "Redmine wiki project"
      description: "The redmine project where the wiki pages are, if not given will export the result in STDOUT"
      type: "string"
    - variable: "WIKI_HOSTS_PAGE"
      label: "Redmine wiki hosts page"
      default: "RancherHosts"
      type: "string"
    - variable: "WIKI_STACKS_PAGE"
      label: "Redmine wiki stacks page"
      default: "RancherStacks"
      type: "string"
    - variable: "WIKI_CONTAINERS_PAGE"
      label: "Redmine wiki containers page"
      default: "RancherContainers"
      type: "string"
    - variable: "DEBUG_ON"
      label: "Debug on"
      default: "No"
      description: "Choose Yes to enable debug logging"
      type: "enum"
      options:
      - "Yes"
      - "No"
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"


      
