name: "Plone"
description: |
  Plone is the premier Python-based CMS
version: "5.1.4-rancher1"
maintainer: "Antonio De Marinis (EEA)"
minimum_rancher_version: v1.0
category: CMS
labels:
  io.rancher.certified: EEA
