version: "2"
catalog:
  name: "SonarQube"
  description: "SonarQube"
  version: "1.0"
  minimum_rancher_version: "v1.2.0"
  questions:
    - variable: JVM_OPTS
      description: "SonarQube web jvm options"
      label: "SonarQube web jvm options"
      required: false
      default: ""
      type: "string"
    - variable: POSTGRES_DB
      description: "Postgres Sonarqube database name"
      label: "Sonarqube database name"
      required: true
      default: "sonar"
      type: "string"
    - variable: POSTGRES_USER
      description: "Postgres Sonarqube user"
      label: "Sonarqube database user"
      required: true
      default: "sonar"
      type: "string"
    - variable: POSTGRES_PASSWORD
      description: "Postgres Sonarqube Password"
      label: "Sonarqube database password"
      required: true
      default: "sonar"
      type: "password"
    - variable: POSTGRES_ADMIN_USER
      description: "Postgres Administrator User"
      label: "Postgres SuperUser"
      default: "postgres"
      type: "string"
    - variable: POSTGRES_ADMIN_PASSWORD
      description: "Postgres Administrator Password"
      label: "Postgres SuperUser Password"
      required: true
      default: "sonar"
      type: "password"
    - variable: "FRONT_HOST_LABELS"
      label: "Schedule Sonarqube on hosts with following host labels"
      description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
      type: "string"
    - variable: "DB_HOST_LABELS"
      label: "Schedule the database on hosts with following host labels"
      description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
      type: "string"
    - variable: "DB_STORAGE_DRIVER"
      label: "Database data volume driver"
      description: "Volume driver for database data"
      default: "local"
      type: "enum"
      options:
        - "rancher-nfs"
        - "rancher-ebs"
        - "local"
      required: true
    - variable: "DB_STORAGE_DRIVER_OPT"
      label: "Database data volume driver options"
      description: |
          Specify "driver_opts" key/value pair in the format "optionName: optionValue".
          E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
      type: "multiline"
    - variable: "FRONT_STORAGE_DRIVER"
      label: "Sonarqube service volumes' driver"
      description: "Driver for all sonarqube volumes"
      default: "rancher-nfs"
        type: "enum"
        options:
          - "rancher-nfs"
          - "rancher-ebs"
          - "local"
      required: true
    - variable: "FRONT_STORAGE_DRIVER_OPT"
      label: "Frontend services volumes' driver options"
      description: |
          Specify "driver_opts" key/value pair in the format "optionName: optionValue".
          E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
      type: "multiline"
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"


services:
  db:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  sonarqube:
    scale: 1
    retain_ip: true
    health_check:
      port: 9000
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
