esapp:
  environment:
    VERSION_INFO: eeacms/esbootstrap:v2.0.7
    elastic_host: elastic
    AUTO_INDEXING: 'false'
    elastic_index: ${es_index_name}
    APP_CONFIG_DIRNAME: global-search
    TZ: ${TZ}
    elastic_rwuser: ${RW_USER}
    elastic_rwpass: ${RW_PASSWORD}
    elastic_rouser: ${RO_USER}
    elastic_ropass: ${RO_PASSWORD}
    elastic_riverindex: global-search_river
  log_driver: ''
  ports:
    - '3000'
  labels:
    io.rancher.sidekicks: esbootstrap-data-config, autosync, rdfriver
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  log_opt: {}
  image: eeacms/esbootstrap:v2.0.7
  volumes_from:
    - esbootstrap-data-config
  links:
    - 'elastic:'

autosync:
  environment:
    VERSION_INFO: eeacms/esbootstrap:v2.0.7
    elastic_host: elastic
    AUTO_INDEXING: 'false'
    SYNC_CRONTAB: ${es_sync_crontab}
    elastic_index: ${es_index_name}
    APP_CONFIG_DIRNAME: global-search
    TZ: ${TZ}
    elastic_rwuser: ${RW_USER}
    elastic_rwpass: ${RW_PASSWORD}
    elastic_rouser: ${RO_USER}
    elastic_ropass: ${RO_PASSWORD}
    elastic_riverindex: global-search_river
  log_driver: ''
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name
  log_opt: {}
  image: eeacms/esbootstrap:v2.0.7
  volumes_from:
    - esbootstrap-data-config
  links:
  - 'elastic:'

esbootstrap-data-config:
  image: eeacms/esbootstrap-configs:v2.0.10
  environment:
    - github_repo=https://github.com/eea/eea.esbootstrap.configs
    - DEV_ENV=false
    - TZ=${TZ}
  volumes:
    - "/code/config"
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name

elastic:
  external_links:
    - ${es_endpoint}
  image: rancher/dns-service

rdfriver:
  environment:
    VERSION_INFO: eeacms/rdfriver:2.0.1
    elastic_host: elastic
    TZ: ${TZ}
    elastic_user: ${RW_USER}
    elastic_pass: ${RW_PASSWORD}
    river_index: global-search_river
    indexer_multithreading: 'false'
    threads: 2
  image: eeacms/rdfriver:2.0.1
  labels:
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  links:
    - 'elastic:'
