.catalog:
  name: "eea-es-bootstrap-global-search"
  version: "2.0.11"
  description: "EEA Global Catalog Search"
  uuid: eea-es-bootstrap-global-search-25
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint. IMPORTANT: elastic data nodes should have at least 1GB Heap size, and 2GB Memory limit"
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: es_index_name
      description: "Set the name of the elasticsearch index. For new deployment make sure the index does not already exist, otherwise it will overwrite the existing one."
      label: "Index name"
      type: "string"
      required: true
      default: global-search
    - variable: "RELEVANCE_SETTINGS"
      label: "Custom relevance settings"
      description: "If empty use the relevance settings from the configuration file. This field should be used only when a quick update is required for relevance. These changes should be moved in esbootstrap-configs."
      type: "multiline"
    - variable: RO_USER
      description: "Read only username"
      label: "Read only username"
      type: "string"
      required: true
      default: "ro"
    - variable: RO_PASSWORD
      description: "Read only user password"
      label: "Read only user password"
      type: "password"
      required: true
      default: "rotest"
    - variable: RW_USER
      description: "RW Username"
      label: "Username with write access"
      type: "string"
      required: true
      default: "rw"
    - variable: RW_PASSWORD
      description: "Read/Write user password"
      label: "Password for RW Username"
      type: "password"
      required: true
      default: "rwtest"
    - variable: es_sync_crontab
      description: "Define the sync frequency for how often your data should be pulled from the sparql endpoint. Use crontab syntax like 0 20 * * *."
      label: "Automatic data synchronisation (sync_crontab)"
      type: string
      default: 30 * * * *
      required: true
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: esbootstrap=yes
    - variable: "SENTRY_DSN"
      label: "Sentry DSN"
      description: "Sentry private DSN"
      type: "string"
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"
esapp:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 5000
rdfriver:
  scale: 1
