version: '2'
services:
  plone:
    image: eeacms/eionet:5.1-1.8
    mem_reservation: 1g
    mem_limit: 2g
    labels:
      io.rancher.scheduler.affinity:host_label_ne: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.eionet.plone: 'true'
    environment:
      ZEO_ADDRESS: zeoserver:8080
      TZ: ${TZ}
  zeoserver:
    image: plone:5.1.5
    mem_reservation: 512m
    mem_limit: 1g
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.eionet.zeoserver: 'true'
    volumes:
    - data:/data
    environment:
      TZ: ${TZ}
    command:
    - zeo

volumes:
  data:
    driver: ${DATA_VOLUME_DRIVER}
    driver_opts:
      {{.Values.DATA_VOLUME_DRIVER_OPTS}}
