name: "Searchlib app"
description: "Search ui based search application"
version: "0.0.1"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
