version: "2"
services:
  logspout:
    image: gliderlabs/logspout:v3.2.5
    environment:
      BACKLOG: "false"
      LOGSPOUT: "ignore"
      SYSLOG_FORMAT: "${format}"
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label_ne: logspout=ignore
      io.rancher.container.hostname_override: container_name
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command:
    - "${route_uri}"
