version: '2'
catalog:
  name: "EEA - Nextcloud"
  description: "Nextcloud file sharing platform"
  version: "1.3"
  questions:
  - variable: "DB_NAME"
    label: "Nextcloud database name"
    description: "Mysql database name"
    type: "string"
    default: "ncdb"
    required: true
  - variable: "DB_USERNAME"
    label: "Nextcloud database username"
    description: "Mysql database username"
    type: "string"
    required: true
    default: "nc"
  - variable: "DB_PASSWORD"
    label: "Nextcloud database user password"
    description: "Mysql database user password"
    type: "password"
    required: true
  - variable: "DB_ROOT_PASSWORD"
    label: "Nextcloud database server root password"
    description: "Mysql server root password"
    type: "password"
    required: true
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTFIX_HOST"
    label: "Postfix hostname"
    type: "string"
  - variable: "POSTFIX_RELAY"
    label: "Postfix relay"
    description: "Postfix SMTP relay"
    type: "string"
    default: "ironports.eea.europa.eu"
  - variable: "POSTFIX_PORT"
    label: "Postfix relay port"
    description: "Postfix SMTP relay port"
    type: "int"
    default: 8587
  - variable: "POSTFIX_USER"
    label: "Postfix user"
    description: "User used to send email"
    type: "string"
  - variable: "POSTFIX_PASS"
    label: "Postfix password"
    description: "Password used to send email"
    type: "password"
  - variable: "NGINX_CONF"
    label: "Nginx configuration"
    description: "169.254.169.250 is used as an internal Rancher DNS"
    type: "multiline"
    default: |
      worker_processes auto;
      
      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;
      
      
      events {
          worker_connections  1024;
      }
      
      
      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;
      
          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';
      
          access_log  /var/log/nginx/access.log  main;
      
          sendfile        on;
          #tcp_nopush     on;
      
          keepalive_timeout  65;
      
          server {
              listen 80;
      
              # Add headers to serve security related headers
              # Before enabling Strict-Transport-Security headers please read into this
              # topic first.
              #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
              #
              # WARNING: Only add the preload option once you read about
              # the consequences in https://hstspreload.org/. This option
              # will add the domain to a hardcoded list that is shipped
              # in all major browsers and getting removed from this list
              # could take several months.
              add_header Referrer-Policy "no-referrer" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-Download-Options "noopen" always;
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Permitted-Cross-Domain-Policies "none" always;
              add_header X-Robots-Tag "none" always;
              add_header X-XSS-Protection "1; mode=block" always;
      
              # Remove X-Powered-By, which is an information leak
              fastcgi_hide_header X-Powered-By;
      
              # Path to the root of your installation
              root /var/www/html;
      
              location = /robots.txt {
                  deny all;
                  log_not_found off;
                  access_log off;
              }
      
              # The following 2 rules are only needed for the user_webfinger app.
              # Uncomment it if you're planning to use this app.
              #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
              #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
      
              # The following rule is only needed for the Social app.
              # Uncomment it if you're planning to use this app.
              #rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
      
              location = /.well-known/carddav {
                  return 301 $scheme://$host:$server_port/remote.php/dav;
              }
      
              location = /.well-known/caldav {
                  return 301 $scheme://$host:$server_port/remote.php/dav;
              }
      
              # set max upload size
              client_max_body_size 10G;
              fastcgi_buffers 64 4K;
      
              # Enable gzip but do not remove ETag headers
              gzip on;
              gzip_vary on;
              gzip_comp_level 4;
              gzip_min_length 256;
              gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
              gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
      
              # Uncomment if your server is build with the ngx_pagespeed module
              # This module is currently not supported.
              #pagespeed off;
      
              location / {
                  rewrite ^ /index.php;
              }
      
              location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
                  deny all;
              }
              location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
                  deny all;
              }
      
              location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+)\.php(?:$|\/) {
                  fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
                  set $path_info $fastcgi_path_info;
                  try_files $fastcgi_script_name =404;
                  include fastcgi_params;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  fastcgi_param PATH_INFO $path_info;
                  # fastcgi_param HTTPS on;
      
                  # Avoid sending the security headers twice
                  fastcgi_param modHeadersAvailable true;
      
                  # Enable pretty urls
                  fastcgi_param front_controller_active true;
                  resolver 169.254.169.250 ipv6=off valid=15s;
                  set $backend "app:9000";
                  fastcgi_pass $backend;
                  fastcgi_intercept_errors on;
                  fastcgi_request_buffering off;
              }
      
              location ~ ^\/(?:updater|oc[ms]-provider)(?:$|\/) {
                  try_files $uri/ =404;
                  index index.php;
              }
      
              # Adding the cache control header for js, css and map files
              # Make sure it is BELOW the PHP block
              location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
                  try_files $uri /index.php$request_uri;
                  add_header Cache-Control "public, max-age=15778463";
                  # Add headers to serve security related headers (It is intended to
                  # have those duplicated to the ones above)
                  # Before enabling Strict-Transport-Security headers please read into
                  # this topic first.
                  #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
                  #
                  # WARNING: Only add the preload option once you read about
                  # the consequences in https://hstspreload.org/. This option
                  # will add the domain to a hardcoded list that is shipped
                  # in all major browsers and getting removed from this list
                  # could take several months.
                  add_header Referrer-Policy "no-referrer" always;
                  add_header X-Content-Type-Options "nosniff" always;
                  add_header X-Download-Options "noopen" always;
                  add_header X-Frame-Options "SAMEORIGIN" always;
                  add_header X-Permitted-Cross-Domain-Policies "none" always;
                  add_header X-Robots-Tag "none" always;
                  add_header X-XSS-Protection "1; mode=block" always;
      
                  # Optional: Don't log access to assets
                  access_log off;
              }
      
              location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap)$ {
                  try_files $uri /index.php$request_uri;
                  # Optional: Don't log access to other assets
                  access_log off;
              }
          }
      }

  - variable: "NEXTCLOUD_APP_MEM"
    label: "Nextcloud server memory reservation & limit"
    description: "At least 2g, per container"
    type: "string"
    required: true
    default: "2g"
  - variable: "NEXTCLOUD_CRON_MEM"
    label: "Nextcloud crontab  memory reservation & limit"
    description: "At least 256m"
    type: "string"
    required: true
    default: "1g"
  - variable: "DB_MEM"
    label: "MariaDB memory reservation & limit"
    description: "At least 1g"
    type: "string"
    required: true
    default: "2g"
  - variable: "REDIS_MEM_RES"
    label: "Redis memory reservation"
    description: "At least 256m"
    type: "string"
    required: true
    default: "512m"
  - variable: "REDIS_MEM_LIMIT"
    label: "Redis memory limit"
    description: "At least 1g"
    type: "string"
    required: true
    default: "1g"
  - variable: "NGINX_MEM_RES"
    label: "Nginx web server memory reservation"
    description: "At least 1g"
    type: "string"
    required: true
    default: "1g"
  - variable: "NGINX_MEM_LIM"
    label: "Nginx web server memory limit"
    description: "At least 1g"
    type: "string"
    required: true
    default: "1g"
  - variable: "VOLUMES_EXTERNAL"
    label: "All stack volumes are external"
    description: "If you choose no, the volumes will be created by the stack"
    default: "Yes"
    type: "enum"
    options:
    - "Yes"
    - "No"
  - variable: "MYSQL_VOLUME"
    label: "MySQL data volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_mysql_data"
    type: "string"
    required: true
  - variable: "MYSQL_VOLUMEDRIVER"
    label: "MySQL data volume driver"
    description: "Volume driver, ignored if external"
    default: "netapp"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    required: true
  - variable: "NEXTCLOUD_DATA"
    label: "Nextcloud share data volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_share_data"
    type: "string"
    required: true
  - variable: "NEXTCLOUD_DATADRIVER"
    label: "Nextcloud share data volume driver, ignored if external"
    description: "Volume driver"
    default: "netapp"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    required: true
  - variable: "NEXTCLOUD_APP"
    label: "Nextcloud application data volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_app_data"
    type: "string"
    required: true
  - variable: "NEXTCLOUD_APPDRIVER"
    label: "Nextcloud application data volume driver, ignored if external"
    description: "Volume driver"
    default: "rancher-nfs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    required: true

  - variable: "NEXTCLOUD_PHP_CONFIG"
    label: "Nextcloud php configuration volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_php_config"
    type: "string"
    required: true
  - variable: "NEXTCLOUD_PHP_CONFIGDRIVER"
    label: "Nextcloud php configuration volume driver, ignored if external"
    description: "Volume driver, do not use rancher-nfs, otherwise you need to manually copy the files"
    default: "netapp"
    type: "enum"
    options:
    - "rancher-ebs"
    - "netapp"
    required: true
  - variable: "NEXTCLOUD_FPM_CONFIG"
    label: "Nextcloud fpm configuration volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_fpm_config"
    type: "string"
    required: true
  - variable: "NEXTCLOUD_FPM_CONFIGDRIVER"
    label: "Nextcloud fpm configuration volume driver, ignored if external"
    description: "Volume driver, do not use rancher-nfs, otherwise you need to manually copy the files"
    default: "netapp"
    type: "enum"
    options:
    - "rancher-ebs"
    - "netapp"
    required: true

  - variable: "REDIS_VOLUME"
    label: "Redis data volume name"
    description: "Volume name (without '-' if using netapp volume driver), needs to be created prior to stack creation if external"
    default: "nextcloud_redis_data"
    type: "string"
    required: true
  - variable: "REDIS_VOLUMEDRIVER"
    label: "Redis data volume driver, ignored if external"
    description: "Volume driver"
    default: "rancher-nfs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "netapp"
    required: true


services:
  app:
    scale: 2 
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 10000
      port: 9000
      unhealthy_threshold: 5
      initializing_timeout: 300000
      interval: 60000
      strategy: recreate
      reinitializing_timeout: 300000
  cron:
    scale: 1
    start_on_create: true
  postfix:
    scale: 1
    start_on_create: true
    health_check:
      port: 25
      interval: 60000
      initializing_timeout: 90000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  redis:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 1
      port: 6379
      unhealthy_threshold: 5
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000    
  db:
    scale: 1
    start_on_create: true
    health_check:
      port: 3306
      interval: 60000
      initializing_timeout: 90000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
