version: '2'
catalog:
  name: "Haystack"
  description: "Haystack - Question Answering at Scale"
  version: "0.7"
  questions:
  - variable: "FARM_API"
    label: "FARM API path"
    description: "Farm API publich url"
    type: "string"
    required: true
    default: "http://farm-api.devel4cph.eea.europa.eu"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    type: "string"
    required: true
  - variable: "JUPYTER_HOST_LABELS"
    label: "Jupyter containers type:"
    type: "enum"
    default: GPU
    required: true
    options:
    - default
    - GPU
  - variable: "HAY_HOST_LABELS"
    label: "Haystack-api containers type:"
    type: "enum"
    default: GPU
    required: true
    options:
    - default
    - GPU
  - variable: "STRM_HOST_LABELS"
    label: "Streamlit containers type:"
    type: "enum"
    default: default
    required: true
    options:
    - default
    - GPU
  - variable: "INFER_HOST_LABELS"
    label: "Inference containers type:"
    type: "enum"
    default: default
    required: true
    options:
    - default
    - GPU
