version: '2'
catalog:
    name: Elasticsearch 6 engine
    version: 6.8-1.0
    description: EEA Elasticsearch cluster to be used with elastic apps

    questions:
        - variable: "cluster_name"
          type: "string"
          required: true
          label: "Cluster name"
          description: "Name of the Elasticsearch Cluster"
          default: "es-cluster"
        - variable: "host_labels"
          description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
          label: "Schedule on hosts with following host labels"
          type: "string"
          default: elastic=yes
        - variable: "UPDATE_SYSCTL"
          label: "Update host sysctl:"
          description: |
            Set true to avoid vm.max_map_count errors. ES will not start without vm.max_map_count updated.
            WARN: If set true, host param vm.max_map_count will be update to 262144.
          default: false
          required: true
          type: enum
          options:
            - false
            - true
        - variable: "ES_CLIENT_PORT"
          label: "ElasticSearch client exposed port"
          description: "Empty if you don't want the ES interface exposed on the server"
          type: "int"
          default: 9200
        - variable: "CEREBRO_PORT"
          label: "Cerebro client exposed port"
          description: "Empty if you don't want the Cerebro web site exposed on the server"
          type: "int"
          default: 9000
        - variable: "KIBANA_PORT"
          label: "Kibana client exposed port"
          description: "Empty if you don't want the Kibana web interface exposed on the server"
          type: "int"
          default: 5601
        - variable: "minimum_master_nodes"
          type: "int"
          required: true
          label: "# of minimum Master Nodes"
          description: "Set the number of required master nodes to reach quorum. Sets initial scale to this value as well"
          default: 1
        - variable: "initial_data_nodes"
          type: "int"
          required: true
          label: "# of initial data nodes"
          description: "Set the initial number of data nodes"
          default: 2
        - variable: "initial_client_nodes"
          type: "int"
          required: true
          label: "# of initial client nodes"
          description: "Set the initial number of client nodes"
          default: 1
        - variable: "ADD_KIBANA"
          label: "Add kibana container:"
          description: |
            Set true to add a Kibana container.
            If false, Kibana will not be added.
          default: true
          required: true
          type: enum
          options:
            - false
            - true
        - variable: "master_heap_size"
          type: "string"
          required: true
          label: "Heap size (master nodes)"
          description: "Heap size to be allocated for Java (master nodes)"
          default: "512m"
        - variable: "master_mem_reservation"
          type: "string"
          required: true
          label: "Memory reservation (master nodes)"
          description: "Memory reservation per elasticsearch container. Recommended - triple the heap size! (master nodes)"
          default: "1536m"
        - variable: "master_mem_limit"
          type: "string"
          required: true
          label: "Memory limit (master nodes)"
          description: "Memory limit per elasticsearch container. Recommended - triple the heap size! (master nodes)"
          default: "1536m"
        - variable: "data_heap_size"
          type: "string"
          required: true
          label: "Heap size (data nodes)"
          description: "Heap size to be allocated for Java (data nodes)"
          default: "512m"
        - variable: "data_mem_reservation"
          type: "string"
          required: true
          label: "Memory reservation (data nodes)"
          description: "Memory reservation per elasticsearch container. Recommended - triple the heap size! (master nodes)"
          default: "1536m"
        - variable: "data_mem_limit"
          type: "string"
          required: true
          label: "Memory limit (data nodes)"
          description: "Memory limit per elasticsearch container.  Recommended - triple the heap size! (data nodes)"
          default: "1536m"
        - variable: "client_heap_size"
          type: "string"
          required: true
          label: "Heap size (client nodes)"
          description: "Heap size to be allocated for Java (client nodes)"
          default: "512m"
        - variable: "client_mem_reservation"
          type: "string"
          required: true
          label: "Memory reservation (client nodes)"
          description: "Memory reservation per elasticsearch container.  Recommended - triple the heap size! (client nodes)"
          default: "1536m"
        - variable: "client_mem_limit"
          type: "string"
          required: true
          label: "Memory limit (client nodes)"
          description: "Memory limit per elasticsearch container. Recommended - triple the heap size! (client nodes)"
          default: "1536m"
        - variable: "CER_JAVA_OPTS"
          type: "string"
          label: "Cerebro Java options"
          description: "Set to limit heap size"
          default: "-J-Xms150m -J-Xmx150m -J-Xss256k -J-XX:MaxMetaspaceSize=100m -J-XX:MaxMetaspaceExpansion=15m -J-XX:CompressedClassSpaceSize=10m -J-XX:ReservedCodeCacheSize=15m -J-XX:+HeapDumpOnOutOfMemoryError -J-XX:+UseCompressedOops"
        - variable: "cerebro_mem_limit"
          type: "string"
          required: true
          label: "Memory limit for cerebro container"
          description: "AT LEAST double the heap size!"
          default: "512m"
        - variable: "cerebro_mem_reservation"
          type: "string"
          required: true
          label: "Memory reservation for cerebro container"
          description: "AT LEAST double the heap size!"
          default: "350m"

        - variable: "kibana_space_size"
          type: "string"
          required: true
          label: "Heap size kibana"
          description: "Used for NodeJs --max-old-space-size setting"
          default: "1024"
        - variable: "kibana_mem_reservation"
          type: "string"
          required: true
          label: "Memory reservation for kibana container"
          description: "AT LEAST the heap size!"
          default: "1024m"
        - variable: "kibana_mem_limit"
          type: "string"
          required: true
          label: "Memory limit for kibana container"
          description: "AT LEAST double the heap size!"
          default: "2048m"

        - variable: "ENABLE_READONLY_REST"
          label: "Enable readonlyrest:"
          description: |
            Set true to install readonlyrest plugin.
            If false, the credentials will not be used.
          default: true
          required: true
          type: enum
          options:
            - false
            - true
        - variable: RO_USER
          description: "Read only username"
          label: "Read only username"
          type: "string"
          default: "ro"
        - variable: RO_PASSWORD
          description: "Read only user password"
          label: "Read only user password"
          type: "password"
          default: "rotest"
        - variable: RW_USER
          description: "RW Username"
          label: "Username with write access"
          type: "string"
          default: "rw"
        - variable: RW_PASSWORD
          description: "Read/Write user password"
          label: "Password for RW Username"
          type: "password"
          default: "rwtest"
        - variable: KIBANA_USER
          description: "KIBANA username"
          label: "kibana username"
          type: "string"
          default: "kibana"
        - variable: KIBANA_PASSWORD
          description: "KIBANA user password"
          label: "kibana user password"
          type: "password"
          default: "kibanatest"
        - variable: KEY_PASSWORD
          description: "ES key password"
          label: "ES https key password"
          type: "password"
        - variable: KEYSTORE_PASSWORD
          description: "ES keystore password"
          label: "ES keystore password"
          type: "password"
        - variable: "TZ"
          label: "Time zone"
          description: "Time zone"
          default: "Europe/Copenhagen"
          required: true
          type: "string"
        - variable: "VOLUME_DRIVER"
          label: "Data volumes driver"
          description: "ElasticSearch data volume driver, choose rancher_ebs only for Amazon"
          default: "rancher-ebs"
          type: "enum"
          options:
          - "rancher-ebs"
          - "rancher-nfs"
          - "netapp"
          - "local"
          required: true
        - variable: "VOLUME_EXTERNAL"
          label: "Data volumes environment scoped (external)"
          description: "ElasticSearch data is environment scoped (externally created by other stack)"
          default: "no"
          type: "enum"
          required: true
          options:
          - "yes"
          - "no"
        - variable: "VOLUME_DRIVER_OPTS"
          label: "Data volume driver options"
          description: |
              Specify "driver_opts" key/value pair in the format "optionName: optionValue".
              E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
              Empty if  driver is not `rancher-ebs`.
          type: "multiline"
          default: "size: 5"
        - variable: "BACKUP_VOLUME_NAME"
          label: "Backup volume name"
          description: "Volume name to manually backup ES data, empty if no backup necessary"
          type: "string"
        - variable: "BACKUP_VOLUME_DRIVER"
          label: "Backup volumes driver"
          description: "ElasticSearch data volume driver, choose rancher_ebs only for Amazon"
          default: "rancher-nfs"
          type: "enum"
          options:
          - "rancher-nfs"
          - "rancher-ebs"
          - "netapp"
          - "local"
        - variable: "BACKUP_VOLUME_EXTERNAL"
          label: "Backup volumes environment scoped (external)"
          description: "ElasticSearch data is environment scoped (externally created by other stack)"
          default: "yes"
          type: "enum"
          options:
          - "yes"
          - "no"
        - variable: "BACKUP_VOLUME_DRIVER_OPTS"
          label: "Backup volume driver options"
          description: |
              Specify "driver_opts" key/value pair in the format "optionName: optionValue".
              E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
              Empty if  driver is not `rancher-ebs`.
          type: "multiline"
          default: ""

services:

  es-master:
    scale: ${minimum_master_nodes}

  es-worker:
    scale: ${initial_data_nodes}

  es-client:
    scale: ${initial_client_nodes}


  cluster-health:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      initializing_timeout: 60000
      port: 12345
      unhealthy_threshold: 3
      interval: 10000
      strategy: none



