name: "Elasticsearch 6 curator"
description: "EEA Elasticsearch 6 index maintenace application"
version: "5.5-1.0"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
