name: "CO2 passenger cars — Elastic app"
description: "Elasticsearch app for CO2 emmisions from passenger cars."
version: "1.0.6"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
