name: "Volto - EPRTR"
description: "Volto - EPRTR: React-based frontend"
version: "0.2-beta.25"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
