name: "Metricbeat Docker Monitoring"
description: "Metricbeat stack for rancher docker container monitoring"
version: "6.3-1"
category: "Monitoring"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
