version: "2"
catalog:
  name: "Cachet"
  description: "Cachet"
  version: "1.0"
  minimum_rancher_version: "v1.2.0"
  questions:
    - variable: CACHET_KEY
      label: "Cachet generated key"
      default: "base64:exKKkzizdjmb+O4ZeQEYU3Rz8eUZhhliPehb2RjPta8="
      required: true
    - variable: CONFIG
      description: "https://github.com/CastawayLabs/cachet-monitor#example-configuration"
      label: "Cachet-monitor configuration"
      required: true
      default: ""
      type: "multiline"
    - variable: DEBUG_ON
      label: "Debug enabled"
      default: "false"
      type: "enum"
      options:
        - "true"
        - "false"
    - variable: POSTGRES_DB
      description: "Postgres Sonarqube database name"
      label: "Sonarqube database name"
      required: true
      default: "sonar"
      type: "string"
    - variable: POSTGRES_USER
      description: "Postgres Sonarqube user"
      label: "Sonarqube database user"
      required: true
      default: "sonar"
      type: "string"
    - variable: POSTGRES_PASSWORD
      description: "Postgres Sonarqube Password"
      label: "Sonarqube database password"
      required: true
      default: "sonar"
      type: "password"
    - variable: "DB_HOST_LABELS"
      label: "Schedule the database on hosts with following host labels"
      description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
      type: "string"
    - variable: "DB_STORAGE_DRIVER"
      label: "Database data volume driver"
      description: "Volume driver for database data"
      default: "netapp"
      type: "enum"
      options:
        - "rancher-nfs"
        - "rancher-ebs"
        - "netapp"
        - "local"
      required: true
    - variable: "DB_STORAGE_DRIVER_OPT"
      label: "Database data volume driver options"
      description: |
          Specify "driver_opts" key/value pair in the format "optionName: optionValue".
          E.g. for the `rancher-ebs` and `netapp` driver you should specify the required 'size' option like this: "size: 1".
      type: "multiline"

    - variable: "CACHET_SERVER_NAME"
      label: "Cachet homeserver public FQDN"
      description: "The hostname of cachet, used to send emails"
      type: "string"
      default: "cachet.eea.europa.eu"
      required: true
    - variable: "POSTFIX_RELAY"
      label: "Postfix relay"
      description: "Postfix SMTP relay"
      type: "string"
      default: "ironports.eea.europa.eu"
    - variable: "POSTFIX_PORT"
      label: "Postfix relay port"
      description: "Postfix SMTP relay port"
      type: "int"
      default: 8587
    - variable: "POSTFIX_USER"
      label: "Postfix user"
      description: "User used to send email"
      type: "string"
    - variable: "POSTFIX_PASS"
      label: "Postfix password"
      description: "Password used for MTP_USER"
      type: "password"

    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"


services:
  db:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  cachet:
    scale: 1
    retain_ip: true
    health_check:
      port: 8000
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
