name: "Copernicus - Land Deployment"
description: "Copernicus Land website."
version: "1.93"
category: "Repository"
maintainer: "EEA: IDM2"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.copernicus//
